### ISSUE TITLE
Exceeded max number of connections. Waiting 60 seconds

### ISSUE THREAD

**Issue by jfrobichaud** [microsoft/Office365DSC#135]
Hi, while running the Export-O365Configuration I get this:
Every 60 Seconds the same warning appear and it doesn't seem to go through.

Extracting EXOSharedMailbox...
WARNING: Exceeded max number of connections. Waiting 60 seconds
WARNING: Exceeded max number of connections. Waiting 60 seconds
WARNING: Exceeded max number of connections. Waiting 60 seconds
WARNING: Exceeded max number of connections. Waiting 60 seconds

Thanks

**Comment by NikCharlebois** [comment]
That is currently the expected behavior with the Exchange Online Management Shell, where there can only be 3 connections made. This normally happens if you ran Export-O365COnfiguration a few times. It is annoying and we are working with the team to find better alternatives that wouldn't require us to forcibly close the connections after every call to EXO, which would have a major negative impact on performance. Leave it running, and the moment one of the connection frees up, it will pick up the extraction. Note that this can sometimes take several minutes to happen.

**Comment by jfrobichaud** [comment]
ok thanks

**Comment by jfrobichaud** [comment]
Still doing this after 1h, is that something I can do to get a connection ? Thanks

**Comment by NikCharlebois** [comment]
Get-PSSession | Remove-PSSession will clear all potential connections, but DSC executes in a different context so you may not be able to close its sessions.

**Comment by NikCharlebois** [comment]
I have been able to reproduce a similar behavior where the Connect-EXO cmdlet retries to connect in an endless loop whenever I use an extraction account that doesn’t have Admin access to Exchange Online. Make sure the account has proper privileges or unchecks all EXO related components before trying the extraction.

**Comment by jfrobichaud** [comment]
I'm trying to extract  O365AdminAuditLogConfig and I don't seem to be able to get a connection after letting the script run for 1 hour.

**Comment by NikCharlebois** [comment]
Please see related issue opened within the Auth module

https://github.com/microsoft/MSCloudLoginAssistant/issues/1

**Comment by NikCharlebois** [comment]
@jfrobichaud please confirm that this is now fixed for you.

**Comment by jfrobichaud** [comment]
Fixed, thanks.
